[package]
name = "uorm-macros"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
glob = "0.3.3"
proc-macro2 = "1.0.103"
quote = "1"
syn = { version = "2.0.111", features = ["full"] }
